class Category_1012 {

class RH_7Rnd_50_AE {type = "trade_items";buy[] = {50,"Coins"};sell[] = {10,"Coins"};};
class RH_6Rnd_44_Mag {type = "trade_items";buy[] = {20,"Coins"};sell[] = {10,"Coins"};};
class RH_6Rnd_357_Mag {type = "trade_items";buy[] = {20,"Coins"};sell[] = {10,"Coins"};};
class RH_13Rnd_9x19_bhp {type = "trade_items";buy[] = {20,"Coins"};sell[] = {10,"Coins"};};
class RH_8Rnd_9x19_P38 {type = "trade_items";buy[] = {20,"Coins"};sell[] = {10,"Coins"};};
class RH_7Rnd_32cal_ppk {type = "trade_items";buy[] = {20,"Coins"};sell[] = {10,"Coins"};};
class RH_8Rnd_9x19_Mk {type = "trade_items";buy[] = {20,"Coins"};sell[] = {10,"Coins"};};
class RH_8Rnd_9x19_Mksd {type = "trade_items";buy[] = {20,"Coins"};sell[] = {10,"Coins"};};
class RH_15Rnd_9x19_usp {type = "trade_items";buy[] = {20,"Coins"};sell[] = {10,"Coins"};};
class RH_15Rnd_9x19_uspsd {type = "trade_items";buy[] = {20,"Coins"};sell[] = {10,"Coins"};};
class RH_12Rnd_45cal_usp {type = "trade_items";buy[] = {20,"Coins"};sell[] = {10,"Coins"};};
class RH_8Rnd_45cal_m1911 {type = "trade_items";buy[] = {20,"Coins"};sell[] = {10,"Coins"};};
class RH_8Rnd_762_tt33 {type = "trade_items";buy[] = {20,"Coins"};sell[] = {10,"Coins"};};
class RH_10Rnd_22LR_mk2 {type = "trade_items";buy[] = {20,"Coins"};sell[] = {10,"Coins"};};
class RH_20Rnd_9x19_M93 {type = "trade_items";buy[] = {20,"Coins"};sell[] = {10,"Coins"};};
class RH_19Rnd_9x19_g18 {type = "trade_items";buy[] = {20,"Coins"};sell[] = {10,"Coins"};};
class RH_17Rnd_9x19_g17 {type = "trade_items";buy[] = {20,"Coins"};sell[] = {10,"Coins"};};
class RH_17Rnd_9x19_g17SD {type = "trade_items";buy[] = {20,"Coins"};sell[] = {10,"Coins"};};
class RH_20Rnd_32cal_vz61 {type = "trade_items";buy[] = {20,"Coins"};sell[] = {10,"Coins"};};
class RH_30Rnd_9x19_tec {type = "trade_items";buy[] = {20,"Coins"};sell[] = {10,"Coins"};};
class RH_32Rnd_9x19_Muzi {type = "trade_items";buy[] = {20,"Coins"};sell[] = {10,"Coins"};};
class vil_bhp_mag {type = "trade_items";buy[] = {20,"Coins"};sell[] = {10,"Coins"};};
class vil_usp45_mag {type = "trade_items";buy[] = {20,"Coins"};sell[] = {10,"Coins"};};
class vil_usp45sd_mag {type = "trade_items";buy[] = {20,"Coins"};sell[] = {10,"Coins"};};
class 17Rnd_9x19_glock17 {type = "trade_items";buy[] = {20,"Coins"};sell[] = {10,"Coins"};};
class 15Rnd_9x19_M9 {type = "trade_items";buy[] = {20,"Coins"};sell[] = {10,"Coins"};};
class 15Rnd_9x19_M9SD {type = "trade_items";buy[] = {20,"Coins"};sell[] = {10,"Coins"};};
class 30Rnd_9x19_MP5 {type = "trade_items";buy[] = {20,"Coins"};sell[] = {10,"Coins"};};
class 30Rnd_9x19_MP5SD {type = "trade_items";buy[] = {20,"Coins"};sell[] = {10,"Coins"};};
class vil_32Rnd_UZI_SD {type = "trade_items";buy[] = {20,"Coins"};sell[] = {10,"Coins"};};
class vil_32Rnd_uzi {type = "trade_items";buy[] = {20,"Coins"};sell[] = {10,"Coins"};};
};
